### ISSUE TITLE
DNS 协议中 dnsMaskString 这个改设置为什么？

### ISSUE THREAD

**Issue by badboycxcc** [Z3ratu1/geacon_plus#7]
这个配置中
```
var (
	// 处理解析的服务器
	dnsServer = "8.8.8.8:53"
	//
	dnsMaskString = ""
	// 域名最后面需要加 .，例如 www.baidu.com.
	serverBaseDomain   = ".baidu.com.."
	dnsBeacon          = ""
	dnsTXT             = "api."
	dnsA               = "cdn."
	dnsAAA             = "www6."
	postResultPrefix   = ""
	postMetadataPrefix = "www."
)
```
dnsMaskString，dnsBeacon，postResultPrefix 默认分别是什么？

**Comment by Z3ratu1** [comment]
请给出更完整的描述，看起来这像是geacon_pro项目的配置文件，然而我目前pro的配置项中应该是没有dnsBeacon这一项的。
mask string对应c2profile中的dns_idle，默认0.0.0.0。postResultPrefix默认值应该是post.

**Comment by badboycxcc** [comment]
是的，这是geacon_pro项目，我已经搞清楚了，已经能过上线和解析命令，但是结果返回似乎格式不对，而且测试发现cs4.5 与4.8 请求格式似乎有不同。

**Comment by Z3ratu1** [comment]
目前只实现了TXT记录的交互模式，是下发命令执行都正常，但返回到C2 server的结果异常吗，给出详细截图，teamserver log，beacon输出等信息

**Comment by badboycxcc** [comment]
已经解决了，是dns 发送数据出现失败情况，原代码没有做重试机制，cs4.5 和 4.8 DNS 协议是一致的，目前均可正常使用
