### ISSUE TITLE
Linux-dns协议无法上线

### ISSUE THREAD

**Issue by 1483769879** [Z3ratu1/geacon_plus#8]
cs4.3，Windows 能正常上线，在 Linux-dns checkin不回来，只有个黑 session，用的是 作者的 jq profile，求救～

**Comment by Z3ratu1** [comment]
怎么回事呢，windows能通linux不能通，但是这段代码在两个操作系统上应该是没有区别的
linux dig一下看看dns解析正不正常之类的？最坏的的情况是wireshark抓个包看看dns请求是什么情况
